#!/usr/bin/env python3
"""Render publication-style benchmark figures and linearized v2 variants."""

from __future__ import annotations

import argparse
import math
import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from tempfile import TemporaryDirectory

os.environ.setdefault("MPLBACKEND", "Agg")

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
from matplotlib import transforms
from matplotlib.ticker import FormatStrFormatter, MaxNLocator


DPI = 300
FIGSIZE = (8.0, 4.5)
MODEL_COLORS = {
    "Baseline CNN": "#0072B2",
    "Random Forest": "#009E73",
    "ExoBiome8 Classical": "#56B4E9",
    "ExoBiome8 Quantum": "#D95F02",
    "ADC2023 Winner Port": "#CC79A7",
    "Local Statevector Simulator": "#6F6F6F",
    "IQM Garnet Hardware": "#E69F00",
}
HIGHLIGHT_LABELS = {"ExoBiome8 Quantum", "ExoBiome"}


@dataclass(frozen=True)
class Datum:
    label: str
    value: float


@dataclass(frozen=True)
class FigureSpec:
    key: str
    filename: str
    title: str
    subtitle: str
    xlabel: str
    data: tuple[Datum, ...]
    chart_type: str = "bar"
    precision: int = 6


FIGURES: tuple[FigureSpec, ...] = (
    FigureSpec(
        key="figure1",
        filename="figure1_adc2023_benchmark.png",
        title="Ariel Data Challenge 2023 Benchmark",
        subtitle="mRMSE comparison on the 5-parameter regression task",
        xlabel="mRMSE (lower is better)",
        data=(
            Datum("ExoBiome8 Quantum", 0.298693),
            Datum("ADC2023 Winner Port", 0.552288),
            Datum("Baseline CNN", 0.650037),
            Datum("Random Forest", 0.757240),
        ),
    ),
    FigureSpec(
        key="figure2",
        filename="figure2_cross_generator_gap.png",
        title="Cross-Generator mRMSE Increase",
        subtitle="Transfer diagnostic: increase from TauREx validation to POSEIDON holdout",
        xlabel="mRMSE increase (lower is better)",
        data=(
            Datum("ExoBiome8 Quantum", 1.766613),
            Datum("ExoBiome8 Classical", 1.856527),
            Datum("ADC2023 Winner Port", 1.970929),
        ),
    ),
    FigureSpec(
        key="figure3",
        filename="figure3_poseidon_holdout.png",
        title="Out-of-Generator mRMSE on POSEIDON Holdout",
        subtitle="TauREx-trained models evaluated on data generated by POSEIDON",
        xlabel="mRMSE (lower is better)",
        data=(
            Datum("ExoBiome8 Quantum", 3.215615),
            Datum("ExoBiome8 Classical", 3.279559),
            Datum("ADC2023 Winner Port", 3.453121),
        ),
    ),
    FigureSpec(
        key="figure4",
        filename="figure4_simulator_vs_garnet.png",
        title="Simulator vs IQM Garnet Under Matched Evaluation",
        subtitle="mRMSE on the same checkpoint and split; values differ by only 0.000105",
        xlabel="mRMSE (lower is better)",
        data=(
            Datum("Local Statevector Simulator", 0.278651),
            Datum("IQM Garnet Hardware", 0.278756),
        ),
        chart_type="hardware",
    ),
)


def pow10_factor(value: float) -> float:
    return math.pow(10.0, value)


LINEARIZED_V2_FIGURES: tuple[FigureSpec, ...] = (
    FigureSpec(
        key="figure1_v2",
        filename="figure1_adc2023_benchmark_v2_linear.png",
        title="Ariel Data Challenge 2023 Benchmark",
        subtitle="Equivalent multiplicative error factor from log10-based mRMSE (10^mRMSE)",
        xlabel="Equivalent error factor (x, lower is better)",
        data=(
            Datum("ExoBiome8 Quantum", pow10_factor(0.298693)),
            Datum("ADC2023 Winner Port", pow10_factor(0.552288)),
            Datum("Baseline CNN", pow10_factor(0.650037)),
            Datum("Random Forest", pow10_factor(0.757240)),
        ),
        precision=3,
    ),
    FigureSpec(
        key="figure2_v2",
        filename="figure2_cross_generator_gap_v2_linear.png",
        title="Cross-Generator Error Inflation",
        subtitle="Multiplicative increase implied by the log10 mRMSE gap (10^ΔmRMSE)",
        xlabel="Inflation factor from TauREx to POSEIDON (x, lower is better)",
        data=(
            Datum("ExoBiome8 Quantum", pow10_factor(1.766613)),
            Datum("ExoBiome8 Classical", pow10_factor(1.856527)),
            Datum("ADC2023 Winner Port", pow10_factor(1.970929)),
        ),
        precision=2,
    ),
    FigureSpec(
        key="figure3_v2",
        filename="figure3_poseidon_holdout_v2_linear.png",
        title="Out-of-Generator Error Factor on POSEIDON Holdout",
        subtitle="Equivalent multiplicative error factor from log10-based mRMSE (10^mRMSE)",
        xlabel="Equivalent error factor (x, lower is better)",
        data=(
            Datum("ExoBiome8 Quantum", pow10_factor(3.215615)),
            Datum("ExoBiome8 Classical", pow10_factor(3.279559)),
            Datum("ADC2023 Winner Port", pow10_factor(3.453121)),
        ),
        precision=1,
    ),
    FigureSpec(
        key="figure4_v2",
        filename="figure4_simulator_vs_garnet_v2_linear.png",
        title="Simulator vs IQM Garnet Under Matched Evaluation",
        subtitle="Equivalent multiplicative error factor from log10-based mRMSE (10^mRMSE)",
        xlabel="Equivalent error factor (x, lower is better)",
        data=(
            Datum("Local Statevector Simulator", pow10_factor(0.278651)),
            Datum("IQM Garnet Hardware", pow10_factor(0.278756)),
        ),
        chart_type="hardware",
        precision=6,
    ),
)


def configure_style() -> None:
    plt.rcParams.update(
        {
            "figure.dpi": DPI,
            "savefig.dpi": DPI,
            "figure.facecolor": "white",
            "savefig.facecolor": "white",
            "axes.facecolor": "white",
            "font.family": "serif",
            "font.serif": ["Times New Roman", "STIXGeneral", "DejaVu Serif"],
            "mathtext.fontset": "stix",
            "axes.linewidth": 0.8,
            "axes.edgecolor": "#1F1F1F",
            "axes.labelcolor": "#1A1A1A",
            "axes.grid": False,
            "xtick.color": "#2A2A2A",
            "ytick.color": "#1A1A1A",
            "xtick.major.width": 0.7,
            "ytick.major.width": 0.0,
            "xtick.major.size": 3.5,
            "ytick.major.size": 0.0,
            "grid.color": "#DEDEDE",
            "grid.linewidth": 0.6,
            "grid.alpha": 1.0,
        }
    )


def add_figure_titles(fig: plt.Figure, spec: FigureSpec) -> None:
    fig.text(0.11, 0.935, spec.title, ha="left", va="top", fontsize=15.0, fontweight="semibold", color="#111111")
    fig.text(0.11, 0.892, spec.subtitle, ha="left", va="top", fontsize=9.6, color="#444444")


def compute_bar_xlim(values: list[float]) -> tuple[float, float]:
    max_value = max(values)
    if max_value < 1.0:
        return 0.0, max_value * 1.16
    return 0.0, max_value * 1.10


def add_bar_labels(ax: plt.Axes, labels: list[str], values: list[float], y_positions: list[int], precision: int) -> None:
    x0, x1 = ax.get_xlim()
    offset = (x1 - x0) * 0.012
    for label, value, y_pos in zip(labels, values, y_positions):
        ax.text(
            value + offset,
            y_pos,
            f"{value:.{precision}f}",
            ha="left",
            va="center",
            fontsize=9.6,
            color=MODEL_COLORS[label] if label in HIGHLIGHT_LABELS else "#111111",
            fontweight="semibold" if label in HIGHLIGHT_LABELS else "normal",
        )


def setup_common_axes(ax: plt.Axes, spec: FigureSpec, labels: list[str], y_positions: list[int]) -> None:
    ax.set_yticks(y_positions)
    ax.set_yticklabels(labels, fontsize=10.2)
    ax.invert_yaxis()
    ax.set_xlabel(spec.xlabel, fontsize=10.2, labelpad=10)
    ax.tick_params(axis="x", labelsize=9.3)
    ax.tick_params(axis="y", pad=10)
    ax.xaxis.grid(True, color="#DDDDDD", linewidth=0.6)
    ax.yaxis.grid(False)
    ax.xaxis.set_major_locator(MaxNLocator(nbins=6))
    ax.xaxis.set_major_formatter(FormatStrFormatter("%.3f"))
    for spine in ("top", "right", "left"):
        ax.spines[spine].set_visible(False)
    ax.spines["bottom"].set_color("#2A2A2A")
    ax.spines["bottom"].set_linewidth(0.8)
    for tick in ax.get_yticklabels():
        if tick.get_text() in HIGHLIGHT_LABELS:
            tick.set_color(MODEL_COLORS[tick.get_text()])
            tick.set_fontweight("semibold")


def annotate_highlight_rows(ax: plt.Axes, labels: list[str], y_positions: list[int]) -> None:
    label_transform = transforms.blended_transform_factory(ax.transAxes, ax.transData)
    for label, y_pos in zip(labels, y_positions):
        if label not in HIGHLIGHT_LABELS:
            continue

        highlight_color = MODEL_COLORS[label]
        line_y = y_pos + 0.17
        text_y = y_pos + 0.33
        ax.plot(
            [-0.30, -0.02],
            [line_y, line_y],
            transform=label_transform,
            color=highlight_color,
            linewidth=1.6,
            solid_capstyle="round",
            clip_on=False,
            zorder=4,
        )
        ax.text(
            -0.30,
            text_y,
            "our model",
            transform=label_transform,
            ha="left",
            va="top",
            fontsize=8.1,
            color=highlight_color,
            fontweight="semibold",
            style="italic",
            clip_on=False,
        )


def draw_bar_chart(spec: FigureSpec, output_path: Path) -> None:
    data = tuple(sorted(spec.data, key=lambda item: item.value))
    labels = [item.label for item in data]
    values = [item.value for item in data]
    colors = [MODEL_COLORS[item.label] for item in data]
    y_positions = list(range(len(data)))

    fig, ax = plt.subplots(figsize=FIGSIZE)
    fig.subplots_adjust(left=0.36, right=0.94, top=0.78, bottom=0.17)
    add_figure_titles(fig, spec)

    for label, value, color, y_pos in zip(labels, values, colors, y_positions):
        is_highlight = label in HIGHLIGHT_LABELS
        ax.barh(
            y_pos,
            value,
            color=color,
            edgecolor="#2A2A2A" if not is_highlight else color,
            linewidth=0.7 if not is_highlight else 1.2,
            height=0.52 if not is_highlight else 0.58,
            zorder=3,
        )
    ax.set_xlim(*compute_bar_xlim(values))
    setup_common_axes(ax, spec, labels, y_positions)
    annotate_highlight_rows(ax, labels, y_positions)
    add_bar_labels(ax, labels, values, y_positions, spec.precision)

    fig.savefig(output_path, dpi=DPI)
    plt.close(fig)


def draw_hardware_chart(spec: FigureSpec, output_path: Path) -> None:
    draw_bar_chart(spec, output_path)


def render_matplotlib_figures(out_dir: Path) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    rendered: list[Path] = []
    for spec in (*FIGURES, *LINEARIZED_V2_FIGURES):
        output_path = out_dir / spec.filename
        if spec.chart_type == "hardware":
            draw_hardware_chart(spec, output_path)
        else:
            draw_bar_chart(spec, output_path)
        rendered.append(output_path)
    return rendered


def escape_tex(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


def latex_bar_document(spec: FigureSpec) -> str:
    data = tuple(sorted(spec.data, key=lambda item: item.value))
    labels = ",".join(escape_tex(item.label) for item in data)
    max_value = max(item.value for item in data) * 1.10
    plot_blocks = []
    for item in data:
        color = MODEL_COLORS[item.label]
        plot_blocks.append(
            "\n".join(
                [
                    rf"\addplot+[xbar, bar width=8pt, draw=black!65, fill={color}] coordinates {{({item.value:.6f},{escape_tex(item.label)})}};",
                    rf"\node[anchor=west, font=\small] at (axis cs:{item.value:.6f},{escape_tex(item.label)}) {{\hspace{{4pt}}\pgfmathprintnumber[fixed,precision=6]{{{item.value:.6f}}}}};",
                ]
            )
        )

    return rf"""
\documentclass[tikz,border=5pt]{{standalone}}
\usepackage{{pgfplots}}
\pgfplotsset{{compat=1.18}}
\begin{{document}}
\begin{{tikzpicture}}
\node[anchor=west, font=\bfseries\fontsize{{14}}{{16}}\selectfont] at (0,7.7) {{{escape_tex(spec.title)}}};
\node[anchor=west, font=\fontsize{{9}}{{11}}\selectfont, text=black!70] at (0,7.15) {{{escape_tex(spec.subtitle)}}};
\begin{{axis}}[
    width=14.1cm,
    height=6.2cm,
    at={{(0,0)}},
    anchor=south west,
    xmin=0,
    xmax={max_value:.6f},
    symbolic y coords={{{labels}}},
    ytick=data,
    y dir=reverse,
    axis x line*=bottom,
    axis y line=none,
    tick align=outside,
    xlabel={{{escape_tex(spec.xlabel)}}},
    xmajorgrids=true,
    ymajorgrids=false,
    grid style={{draw=black!12}},
    xticklabel style={{font=\small}},
    yticklabel style={{font=\normalsize}},
    enlarge y limits=0.22,
]
{os.linesep.join(plot_blocks)}
\end{{axis}}
\end{{tikzpicture}}
\end{{document}}
""".strip() + "\n"


def emit_latex_sources(latex_dir: Path) -> list[Path]:
    latex_dir.mkdir(parents=True, exist_ok=True)
    rendered: list[Path] = []
    latex_specs = [spec for spec in FIGURES if spec.key in {"figure1", "figure3"}]
    for spec in latex_specs:
        tex_path = latex_dir / f"{Path(spec.filename).stem}.tex"
        tex_path.write_text(latex_bar_document(spec), encoding="utf-8")
        rendered.append(tex_path)
    return rendered


def convert_pdf_to_png(pdf_path: Path, output_png: Path) -> bool:
    if shutil.which("qlmanage") is None:
        return False

    with TemporaryDirectory() as tmp_dir:
        result = subprocess.run(
            ["qlmanage", "-t", "-s", "2400", "-o", tmp_dir, str(pdf_path)],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            return False
        thumbnail = Path(tmp_dir) / f"{pdf_path.name}.png"
        if not thumbnail.exists():
            thumbnail = Path(tmp_dir) / f"{pdf_path.stem}.pdf.png"
        if not thumbnail.exists():
            return False
        shutil.copy2(thumbnail, output_png)
    return True


def try_compile_latex_sources(tex_paths: list[Path], latex_dir: Path) -> list[Path]:
    rendered_pngs: list[Path] = []
    tectonic = shutil.which("tectonic") or "/opt/homebrew/bin/tectonic"
    if not Path(tectonic).exists():
        print("LATEX_COMPILE_SKIPPED: tectonic not found")
        return rendered_pngs

    for tex_path in tex_paths:
        try:
            result = subprocess.run(
                [tectonic, str(tex_path)],
                cwd=latex_dir,
                capture_output=True,
                text=True,
                timeout=180,
            )
        except subprocess.TimeoutExpired:
            print(f"LATEX_COMPILE_TIMEOUT: {tex_path.name}")
            continue

        if result.returncode != 0:
            print(f"LATEX_COMPILE_FAILED: {tex_path.name}")
            stderr = (result.stderr or "").strip()
            if stderr:
                print(stderr[:1000])
            continue

        pdf_path = tex_path.with_suffix(".pdf")
        png_path = tex_path.with_suffix(".png")
        if pdf_path.exists() and convert_pdf_to_png(pdf_path, png_path):
            rendered_pngs.append(png_path)
            print(f"LATEX_PNG_RENDERED: {png_path}")
        else:
            print(f"LATEX_PDF_READY: {pdf_path}")
    return rendered_pngs


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render publication-style hackathon figures.")
    parser.add_argument(
        "--out-dir",
        default="outputs/presentation_figures",
        help="Output directory for the matplotlib-rendered PNG figures.",
    )
    parser.add_argument(
        "--latex-out-dir",
        default="outputs/presentation_figures_latex",
        help="Output directory for LaTeX comparison source files and rendered assets.",
    )
    parser.add_argument(
        "--no-latex-sources",
        action="store_true",
        help="Skip LaTeX source generation.",
    )
    parser.add_argument(
        "--compile-latex",
        action="store_true",
        help="Attempt to compile the emitted LaTeX sources to PDF/PNG.",
    )
    return parser.parse_args()


def main() -> int:
    configure_style()
    args = parse_args()

    out_dir = Path(args.out_dir).resolve()
    latex_out_dir = Path(args.latex_out_dir).resolve()

    for path in render_matplotlib_figures(out_dir):
        print(path)

    if not args.no_latex_sources:
        tex_paths = emit_latex_sources(latex_out_dir)
        for path in tex_paths:
            print(path)
        if args.compile_latex:
            for path in try_compile_latex_sources(tex_paths, latex_out_dir):
                print(path)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
